import type { Listing } from "./types";

/** Official Nifty 50 cash names (desk book). */
const NIFTY_50_SYMBOLS = new Set([
  "ADANIENT",
  "ADANIPORTS",
  "APOLLOHOSP",
  "ASIANPAINT",
  "AXISBANK",
  "BAJAJ-AUTO",
  "BAJAJFINSV",
  "BAJFINANCE",
  "BEL",
  "BHARTIARTL",
  "BPCL",
  "BRITANNIA",
  "CIPLA",
  "COALINDIA",
  "DRREDDY",
  "EICHERMOT",
  "GRASIM",
  "HCLTECH",
  "HDFCBANK",
  "HDFCLIFE",
  "HEROMOTOCO",
  "HINDALCO",
  "HINDUNILVR",
  "ICICIBANK",
  "INFY",
  "ITC",
  "JIOFIN",
  "JSWSTEEL",
  "KOTAKBANK",
  "LT",
  "M&M",
  "MARUTI",
  "NESTLEIND",
  "NTPC",
  "ONGC",
  "POWERGRID",
  "RELIANCE",
  "SBILIFE",
  "SBIN",
  "SHRIRAMFIN",
  "SUNPHARMA",
  "TATACONSUM",
  "TATAMOTORS",
  "TATASTEEL",
  "TCS",
  "TECHM",
  "TITAN",
  "TRENT",
  "ULTRACEMCO",
  "WIPRO",
]);

/** Desk reference market cap in ₹ crore. */
const NIFTY_50_MCAP_CR: Record<string, number> = {
  RELIANCE: 1842000,
  TCS: 1418000,
  HDFCBANK: 1275000,
  BHARTIARTL: 1186000,
  ICICIBANK: 982000,
  INFY: 724000,
  SBIN: 708000,
  ITC: 618000,
  HINDUNILVR: 576000,
  LT: 534000,
  BAJFINANCE: 512000,
  HCLTECH: 468000,
  MARUTI: 428000,
  "M&M": 412000,
  SUNPHARMA: 398000,
  AXISBANK: 376000,
  KOTAKBANK: 354000,
  ULTRACEMCO: 338000,
  TITAN: 322000,
  NTPC: 318000,
  BAJAJFINSV: 306000,
  ONGC: 302000,
  ADANIENT: 288000,
  POWERGRID: 276000,
  WIPRO: 272000,
  ADANIPORTS: 268000,
  TRENT: 264000,
  "BAJAJ-AUTO": 252000,
  BEL: 248000,
  TATAMOTORS: 246000,
  COALINDIA: 238000,
  JSWSTEEL: 228000,
  NESTLEIND: 226000,
  ASIANPAINT: 218000,
  TATASTEEL: 198000,
  JIOFIN: 192000,
  GRASIM: 184000,
  SBILIFE: 164000,
  HDFCLIFE: 146000,
  EICHERMOT: 144000,
  BRITANNIA: 138000,
  HINDALCO: 148000,
  TECHM: 136000,
  BPCL: 128000,
  SHRIRAMFIN: 126000,
  CIPLA: 124000,
  TATACONSUM: 118000,
  DRREDDY: 112000,
  APOLLOHOSP: 108000,
  HEROMOTOCO: 94000,
};

/** NSE cash-equity book used by this desk (Nifty 50 plus broader coverage). */
const rows: [string, string, string, number][] = [
  ["RELIANCE", "Reliance Industries", "Energy", 1390],
  ["TCS", "Tata Consultancy Services", "IT", 3920],
  ["HDFCBANK", "HDFC Bank", "Financials", 1680],
  ["ICICIBANK", "ICICI Bank", "Financials", 1285],
  ["INFY", "Infosys", "IT", 1560],
  ["ITC", "ITC", "FMCG", 430],
  ["BHARTIARTL", "Bharti Airtel", "Telecom", 1720],
  ["SBIN", "State Bank of India", "Financials", 810],
  ["LT", "Larsen & Toubro", "Industrials", 3620],
  ["HINDUNILVR", "Hindustan Unilever", "FMCG", 2480],
  ["BAJFINANCE", "Bajaj Finance", "Financials", 7180],
  ["KOTAKBANK", "Kotak Mahindra Bank", "Financials", 1785],
  ["AXISBANK", "Axis Bank", "Financials", 1120],
  ["ASIANPAINT", "Asian Paints", "Consumer", 2320],
  ["MARUTI", "Maruti Suzuki", "Auto", 12450],
  ["SUNPHARMA", "Sun Pharmaceutical", "Pharma", 1780],
  ["TITAN", "Titan Company", "Consumer", 3380],
  ["ULTRACEMCO", "UltraTech Cement", "Materials", 11420],
  ["NESTLEIND", "Nestle India", "FMCG", 2280],
  ["WIPRO", "Wipro", "IT", 268],
  ["M&M", "Mahindra & Mahindra", "Auto", 2890],
  ["POWERGRID", "Power Grid Corporation", "Utilities", 318],
  ["NTPC", "NTPC", "Utilities", 368],
  ["HCLTECH", "HCL Technologies", "IT", 1620],
  ["TATAMOTORS", "Tata Motors", "Auto", 720],
  ["TATASTEEL", "Tata Steel", "Metals", 148],
  ["JSWSTEEL", "JSW Steel", "Metals", 920],
  ["ADANIENT", "Adani Enterprises", "Conglomerate", 2480],
  ["ADANIPORTS", "Adani Ports", "Infrastructure", 1185],
  ["COALINDIA", "Coal India", "Energy", 398],
  ["ONGC", "Oil & Natural Gas Corp", "Energy", 248],
  ["BAJAJFINSV", "Bajaj Finserv", "Financials", 1680],
  ["BEL", "Bharat Electronics", "Industrials", 285],
  ["TRENT", "Trent", "Consumer", 5420],
  ["INDUSINDBK", "IndusInd Bank", "Financials", 980],
  ["TECHM", "Tech Mahindra", "IT", 1520],
  ["GRASIM", "Grasim Industries", "Materials", 2580],
  ["CIPLA", "Cipla", "Pharma", 1485],
  ["DRREDDY", "Dr. Reddy's Laboratories", "Pharma", 1280],
  ["EICHERMOT", "Eicher Motors", "Auto", 4920],
  ["HINDALCO", "Hindalco Industries", "Metals", 650],
  ["APOLLOHOSP", "Apollo Hospitals", "Healthcare", 6420],
  ["TATACONSUM", "Tata Consumer Products", "FMCG", 1125],
  ["HDFCLIFE", "HDFC Life", "Financials", 690],
  ["SBILIFE", "SBI Life Insurance", "Financials", 1560],
  ["DIVISLAB", "Divi's Laboratories", "Pharma", 4920],
  ["BPCL", "Bharat Petroleum", "Energy", 310],
  ["BRITANNIA", "Britannia Industries", "FMCG", 5380],
  ["HEROMOTOCO", "Hero MotoCorp", "Auto", 4480],
  ["SHRIRAMFIN", "Shriram Finance", "Financials", 2920],
  ["ADANIGREEN", "Adani Green Energy", "Utilities", 1025],
  ["ADANIPOWER", "Adani Power", "Utilities", 548],
  ["AMBUJACEM", "Ambuja Cements", "Materials", 548],
  ["BAJAJ-AUTO", "Bajaj Auto", "Auto", 8920],
  ["BANKBARODA", "Bank of Baroda", "Financials", 248],
  ["CANBK", "Canara Bank", "Financials", 108],
  ["CHOLAFIN", "Cholamandalam Investment", "Financials", 1285],
  ["DABUR", "Dabur India", "FMCG", 512],
  ["DLF", "DLF", "Realty", 780],
  ["GAIL", "GAIL India", "Energy", 188],
  ["GODREJCP", "Godrej Consumer Products", "FMCG", 1180],
  ["HAVELLS", "Havells India", "Industrials", 1680],
  ["ICICIGI", "ICICI Lombard", "Financials", 1880],
  ["ICICIPRULI", "ICICI Prudential Life", "Financials", 640],
  ["INDIGO", "InterGlobe Aviation", "Aviation", 4320],
  ["IOC", "Indian Oil Corporation", "Energy", 148],
  ["IRCTC", "IRCTC", "Consumer", 780],
  ["JINDALSTEL", "Jindal Steel & Power", "Metals", 920],
  ["LICI", "Life Insurance Corp", "Financials", 890],
  ["LODHA", "Macrotech Developers", "Realty", 1180],
  ["PIDILITIND", "Pidilite Industries", "Materials", 2980],
  ["PNB", "Punjab National Bank", "Financials", 108],
  ["RECLTD", "REC Limited", "Financials", 478],
  ["SBICARD", "SBI Cards", "Financials", 780],
  ["SIEMENS", "Siemens India", "Industrials", 3180],
  ["TATAPOWER", "Tata Power", "Utilities", 398],
  ["TVSMOTOR", "TVS Motor", "Auto", 2480],
  ["UNIONBANK", "Union Bank of India", "Financials", 128],
  ["VEDL", "Vedanta", "Metals", 448],
  ["YESBANK", "Yes Bank", "Financials", 22],
  ["ZYDUSLIFE", "Zydus Lifesciences", "Pharma", 980],
  ["ABB", "ABB India", "Industrials", 5920],
  ["ACC", "ACC", "Materials", 2120],
  ["ALKEM", "Alkem Laboratories", "Pharma", 5380],
  ["ASHOKLEY", "Ashok Leyland", "Auto", 218],
  ["ASTRAL", "Astral", "Materials", 1480],
  ["ATGL", "Adani Total Gas", "Energy", 648],
  ["AUBANK", "AU Small Finance Bank", "Financials", 648],
  ["AUROPHARMA", "Aurobindo Pharma", "Pharma", 1280],
  ["BANDHANBNK", "Bandhan Bank", "Financials", 168],
  ["BERGEPAINT", "Berger Paints", "Consumer", 498],
  ["BHARATFORG", "Bharat Forge", "Auto", 1280],
  ["BHEL", "BHEL", "Industrials", 228],
  ["BIOCON", "Biocon", "Pharma", 348],
  ["BOSCHLTD", "Bosch", "Auto", 31800],
  ["BSE", "BSE Limited", "Financials", 2480],
  ["CGPOWER", "CG Power", "Industrials", 680],
  ["COLPAL", "Colgate-Palmolive India", "FMCG", 2680],
  ["CONCOR", "Container Corporation", "Infrastructure", 848],
  ["CUMMINSIND", "Cummins India", "Industrials", 3280],
  ["DALBHARAT", "Dalmia Bharat", "Materials", 1780],
  ["DEEPAKNTR", "Deepak Nitrite", "Materials", 2280],
  ["DIXON", "Dixon Technologies", "Consumer", 14820],
  ["DMART", "Avenue Supermarts", "Consumer", 3920],
  ["FEDERALBNK", "Federal Bank", "Financials", 188],
  ["FORTIS", "Fortis Healthcare", "Healthcare", 548],
  ["GODREJPROP", "Godrej Properties", "Realty", 2480],
  ["HAL", "Hindustan Aeronautics", "Industrials", 4280],
  ["HDFCAMC", "HDFC AMC", "Financials", 4180],
  ["HINDPETRO", "Hindustan Petroleum", "Energy", 398],
  ["HONAUT", "Honeywell Automation", "Industrials", 42800],
  ["IDFCFIRSTB", "IDFC First Bank", "Financials", 72],
  ["IEX", "Indian Energy Exchange", "Utilities", 178],
  ["IGL", "Indraprastha Gas", "Energy", 198],
  ["INDUSTOWER", "Indus Towers", "Telecom", 368],
  ["INFIBEAM", "Infibeam Avenues", "IT", 28],
  ["IPCALAB", "Ipca Laboratories", "Pharma", 1480],
  ["IRFC", "IRFC", "Financials", 148],
  ["JIOFIN", "Jio Financial Services", "Financials", 318],
  ["JUBLFOOD", "Jubilant FoodWorks", "Consumer", 648],
  ["KPITTECH", "KPIT Technologies", "IT", 1280],
  ["LALPATHLAB", "Dr Lal PathLabs", "Healthcare", 2980],
  ["LICHSGFIN", "LIC Housing Finance", "Financials", 598],
  ["LTTS", "L&T Technology Services", "IT", 4480],
  ["LUPIN", "Lupin", "Pharma", 1980],
  ["MOTHERSON", "Samvardhana Motherson", "Auto", 148],
  ["MPHASIS", "Mphasis", "IT", 2680],
  ["MRF", "MRF", "Auto", 128500],
  ["MUTHOOTFIN", "Muthoot Finance", "Financials", 1980],
  ["NAUKRI", "Info Edge", "IT", 6980],
  ["NHPC", "NHPC", "Utilities", 82],
  ["NMDC", "NMDC", "Metals", 72],
  ["NYKAA", "FSN E-Commerce (Nykaa)", "Consumer", 168],
  ["OBEROIRLTY", "Oberoi Realty", "Realty", 1680],
  ["OFSS", "Oracle Financial Services", "IT", 9180],
  ["OIL", "Oil India", "Energy", 448],
  ["PAGEIND", "Page Industries", "Consumer", 41800],
  ["PAYTM", "One97 Communications", "IT", 720],
  ["PERSISTENT", "Persistent Systems", "IT", 5480],
  ["PETRONET", "Petronet LNG", "Energy", 318],
  ["PFC", "Power Finance Corporation", "Financials", 448],
  ["PGHH", "P&G Hygiene", "FMCG", 14880],
  ["PIIND", "PI Industries", "Materials", 3680],
  ["POLYCAB", "Polycab India", "Industrials", 5980],
  ["POLICYBZR", "PB Fintech", "Financials", 1580],
  ["PRESTIGE", "Prestige Estates", "Realty", 1480],
  ["PVRINOX", "PVR INOX", "Media", 1480],
  ["RAMCOCEM", "The Ramco Cements", "Materials", 848],
  ["SAIL", "Steel Authority of India", "Metals", 118],
  ["SHREECEM", "Shree Cement", "Materials", 26800],
  ["SOLARINDS", "Solar Industries", "Materials", 9780],
  ["SONACOMS", "Sona BLW Precision", "Auto", 580],
  ["SRF", "SRF", "Materials", 2280],
  ["SUPREMEIND", "Supreme Industries", "Materials", 4280],
  ["SYNGENE", "Syngene International", "Pharma", 780],
  ["TATACHEM", "Tata Chemicals", "Materials", 980],
  ["TATAELXSI", "Tata Elxsi", "IT", 5980],
  ["TATATECH", "Tata Technologies", "IT", 780],
  ["TORNTPHARM", "Torrent Pharmaceuticals", "Pharma", 3180],
  ["TORNTPOWER", "Torrent Power", "Utilities", 1480],
  ["UBL", "United Breweries", "FMCG", 1980],
  ["UNITDSPR", "United Spirits", "FMCG", 1480],
  ["UPL", "UPL", "Materials", 548],
  ["VBL", "Varun Beverages", "FMCG", 548],
  ["VOLTAS", "Voltas", "Consumer", 1480],
  ["ZOMATO", "Eternal (Zomato)", "Consumer", 248],
  ["ABCAPITAL", "Aditya Birla Capital", "Financials", 218],
  ["ABFRL", "Aditya Birla Fashion", "Consumer", 268],
  ["AEGISLOG", "Aegis Logistics", "Energy", 748],
  ["AFFLE", "Affle India", "IT", 1680],
  ["AJANTPHARM", "Ajanta Pharma", "Pharma", 2780],
  ["APLAPOLLO", "APL Apollo Tubes", "Metals", 1480],
  ["BALKRISIND", "Balkrishna Industries", "Auto", 2680],
  ["BATAINDIA", "Bata India", "Consumer", 1280],
  ["CAMS", "Computer Age Management", "Financials", 3980],
  ["CDSL", "CDSL", "Financials", 1480],
  ["COFORGE", "Coforge", "IT", 7980],
  ["CROMPTON", "Crompton Greaves Consumer", "Consumer", 348],
  ["CYIENT", "Cyient", "IT", 1480],
  ["DELHIVERY", "Delhivery", "Infrastructure", 348],
  ["ESCORTS", "Escorts Kubota", "Auto", 3480],
  ["EXIDEIND", "Exide Industries", "Auto", 398],
  ["GLAND", "Gland Pharma", "Pharma", 1680],
  ["GLENMARK", "Glenmark Pharmaceuticals", "Pharma", 1480],
  ["GMRINFRA", "GMR Airports", "Infrastructure", 82],
  ["GSPL", "Gujarat State Petronet", "Energy", 348],
  ["HFCL", "HFCL", "Telecom", 108],
  ["IIFL", "IIFL Finance", "Financials", 428],
  ["INOXWIND", "Inox Wind", "Utilities", 168],
  ["JBCHEPHARM", "J.B. Chemicals", "Pharma", 1680],
  ["KALYANKJIL", "Kalyan Jewellers", "Consumer", 548],
  ["KEI", "KEI Industries", "Industrials", 3980],
  ["LAURUSLABS", "Laurus Labs", "Pharma", 548],
  ["MANKIND", "Mankind Pharma", "Pharma", 2480],
  ["MAXHEALTH", "Max Healthcare", "Healthcare", 980],
  ["MCX", "Multi Commodity Exchange", "Financials", 5980],
  ["METROPOLIS", "Metropolis Healthcare", "Healthcare", 1980],
  ["MFSL", "Max Financial Services", "Financials", 1180],
  ["NATIONALUM", "National Aluminium", "Metals", 198],
  ["NAVINFLUOR", "Navin Fluorine", "Materials", 3480],
  ["NIACL", "New India Assurance", "Financials", 198],
  ["PATANJALI", "Patanjali Foods", "FMCG", 1680],
  ["PHOENIXLTD", "Phoenix Mills", "Realty", 1580],
  ["POONAWALLA", "Poonawalla Fincorp", "Financials", 348],
  ["RADICO", "Radico Khaitan", "FMCG", 1980],
  ["RAILTEL", "RailTel Corporation", "Telecom", 398],
  ["RBLBANK", "RBL Bank", "Financials", 168],
  ["RVNL", "Rail Vikas Nigam", "Infrastructure", 398],
  ["SJVN", "SJVN", "Utilities", 108],
  ["STARHEALTH", "Star Health", "Financials", 498],
  ["SUNTV", "Sun TV Network", "Media", 680],
  ["SUZLON", "Suzlon Energy", "Utilities", 58],
  ["TATACOMM", "Tata Communications", "Telecom", 1680],
  ["TIINDIA", "Tube Investments", "Auto", 2980],
  ["TIMKEN", "Timken India", "Industrials", 2980],
  ["TITAGARH", "Titagarh Rail Systems", "Industrials", 980],
  ["UNIONBANK", "Union Bank of India", "Financials", 128],
  ["WAAREEENER", "Waaree Energies", "Utilities", 2480],
  ["MANYAVAR", "Vedant Fashions", "Consumer", 980],
  ["KFINTECH", "KFin Technologies", "Financials", 980],
  ["ANGELONE", "Angel One", "Financials", 2480],
  ["IDEA", "Vodafone Idea", "Telecom", 12],
  ["TATAMTRDVR", "Tata Motors DVR", "Auto", 480],
  ["NH", "Narayana Hrudayalaya", "Healthcare", 1280],
  ["KEC", "KEC International", "Infrastructure", 848],
  ["BLUESTARCO", "Blue Star", "Consumer", 1780],
  ["THERMAX", "Thermax", "Industrials", 4480],
  ["SCHAEFFLER", "Schaeffler India", "Auto", 3480],
  ["SKFINDIA", "SKF India", "Industrials", 4980],
  ["3MINDIA", "3M India", "Conglomerate", 29800],
  ["CRISIL", "CRISIL", "Financials", 4480],
  ["ENDURANCE", "Endurance Technologies", "Auto", 2280],
  ["LINDEINDIA", "Linde India", "Materials", 6480],
  ["AIAENG", "AIA Engineering", "Industrials", 3680],
  ["APOLLOTYRE", "Apollo Tyres", "Auto", 448],
  ["BALRAMCHIN", "Balrampur Chini", "FMCG", 548],
  ["CESC", "CESC", "Utilities", 168],
  ["CHAMBLFERT", "Chambal Fertilisers", "Materials", 498],
  ["COROMANDEL", "Coromandel International", "Materials", 1680],
  ["CREDITACC", "CreditAccess Grameen", "Financials", 1280],
  ["DEVYANI", "Devyani International", "Consumer", 168],
  ["ELGIEQUIP", "Elgi Equipments", "Industrials", 548],
  ["FACT", "FACT", "Materials", 848],
  ["FINCABLES", "Finolex Cables", "Industrials", 980],
  ["FIVESTAR", "Five-Star Business Finance", "Financials", 748],
  ["FLUOROCHEM", "Gujarat Fluorochemicals", "Materials", 3980],
  ["GICRE", "GIC Re", "Financials", 398],
  ["GNFC", "GNFC", "Materials", 548],
  ["GRAPHITE", "Graphite India", "Materials", 548],
  ["GMDCLTD", "Gujarat Mineral Dev", "Metals", 348],
  ["HATSUN", "Hatsun Agro", "FMCG", 980],
  ["HEG", "HEG", "Materials", 1980],
  ["IIFLWAM", "360 ONE WAM", "Financials", 980],
  ["INTELLECT", "Intellect Design Arena", "IT", 848],
  ["JBMA", "JBM Auto", "Auto", 680],
  ["JSL", "Jindal Stainless", "Metals", 680],
  ["KIRLOSENG", "Kirloskar Oil Engines", "Industrials", 980],
  ["KPIL", "Kalpataru Projects", "Infrastructure", 1180],
  ["MAZDOCK", "Mazagon Dock", "Industrials", 2280],
  ["MEDPLUS", "Medplus Health", "Healthcare", 748],
  ["NATCOPHARM", "Natco Pharma", "Pharma", 1280],
  ["NBCC", "NBCC India", "Infrastructure", 108],
  ["NCC", "NCC Limited", "Infrastructure", 248],
  ["PPLPHARMA", "Piramal Pharma", "Pharma", 218],
  ["PRAJIND", "Praj Industries", "Industrials", 548],
  ["RATNAMANI", "Ratnamani Metals", "Metals", 2980],
  ["REDINGTON", "Redington", "IT", 198],
  ["ROUTE", "Route Mobile", "IT", 1280],
  ["SAPPHIRE", "Sapphire Foods", "Consumer", 1480],
  ["SHYAMMETL", "Shyam Metalics", "Metals", 748],
  ["SONATSOFTW", "Sonata Software", "IT", 548],
  ["SUMICHEM", "Sumitomo Chemical India", "Materials", 498],
  ["SUNDRMFAST", "Sundram Fasteners", "Auto", 1280],
  ["TANLA", "Tanla Platforms", "IT", 648],
  ["TEJASNET", "Tejas Networks", "Telecom", 980],
  ["TRITURBINE", "Triveni Turbine", "Industrials", 548],
  ["USHAMART", "Usha Martin", "Metals", 348],
  ["WELCORP", "Welspun Corp", "Metals", 748],
  ["WESTLIFE", "Westlife Foodworld", "Consumer", 680],
  ["ZEEL", "Zee Entertainment", "Media", 128],
];

const seen = new Set<string>();
export const NSE_LISTINGS: Listing[] = rows
  .filter(([symbol]) => {
    if (seen.has(symbol)) return false;
    seen.add(symbol);
    return true;
  })
  .map(([symbol, name, sector, startPrice]) => ({
    symbol,
    name,
    sector,
    startPrice,
    marketCap: NIFTY_50_MCAP_CR[symbol] ?? Math.round(startPrice * 40),
  }));

export const NIFTY50_LISTINGS: Listing[] = NSE_LISTINGS.filter((row) =>
  NIFTY_50_SYMBOLS.has(row.symbol),
).sort((a, b) => a.symbol.localeCompare(b.symbol));
