import type { Listing } from "./types";

/** Top 50 US names by desk-reference market cap. */
export const US_LISTINGS: Listing[] = [
  { symbol: "NVDA", name: "NVIDIA", sector: "Tech", startPrice: 120, marketCap: 4.52e12 },
  { symbol: "MSFT", name: "Microsoft", sector: "Tech", startPrice: 410, marketCap: 3.81e12 },
  { symbol: "AAPL", name: "Apple", sector: "Tech", startPrice: 220, marketCap: 3.58e12 },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer", startPrice: 180, marketCap: 2.41e12 },
  { symbol: "GOOGL", name: "Alphabet", sector: "Tech", startPrice: 165, marketCap: 2.18e12 },
  { symbol: "META", name: "Meta", sector: "Tech", startPrice: 500, marketCap: 1.82e12 },
  { symbol: "AVGO", name: "Broadcom", sector: "Tech", startPrice: 340, marketCap: 1.61e12 },
  { symbol: "TSLA", name: "Tesla", sector: "Auto", startPrice: 240, marketCap: 1.22e12 },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", startPrice: 480, marketCap: 1.05e12 },
  { symbol: "JPM", name: "JPMorgan", sector: "Financials", startPrice: 200, marketCap: 8.24e11 },
  { symbol: "WMT", name: "Walmart", sector: "Consumer", startPrice: 95, marketCap: 7.86e11 },
  { symbol: "LLY", name: "Eli Lilly", sector: "Health", startPrice: 780, marketCap: 7.42e11 },
  { symbol: "V", name: "Visa", sector: "Financials", startPrice: 310, marketCap: 6.98e11 },
  { symbol: "ORCL", name: "Oracle", sector: "Tech", startPrice: 220, marketCap: 6.74e11 },
  { symbol: "MA", name: "Mastercard", sector: "Financials", startPrice: 520, marketCap: 5.18e11 },
  { symbol: "NFLX", name: "Netflix", sector: "Media", startPrice: 700, marketCap: 4.86e11 },
  { symbol: "XOM", name: "Exxon", sector: "Energy", startPrice: 110, marketCap: 4.81e11 },
  { symbol: "COST", name: "Costco", sector: "Consumer", startPrice: 920, marketCap: 4.46e11 },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health", startPrice: 165, marketCap: 4.22e11 },
  { symbol: "HD", name: "Home Depot", sector: "Consumer", startPrice: 400, marketCap: 4.02e11 },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer", startPrice: 170, marketCap: 3.94e11 },
  { symbol: "ABBV", name: "AbbVie", sector: "Health", startPrice: 190, marketCap: 3.78e11 },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", startPrice: 42, marketCap: 3.66e11 },
  { symbol: "PLTR", name: "Palantir", sector: "Tech", startPrice: 160, marketCap: 3.58e11 },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer", startPrice: 70, marketCap: 3.21e11 },
  { symbol: "UNH", name: "UnitedHealth", sector: "Health", startPrice: 350, marketCap: 3.12e11 },
  { symbol: "CRM", name: "Salesforce", sector: "Tech", startPrice: 270, marketCap: 2.98e11 },
  { symbol: "CSCO", name: "Cisco", sector: "Tech", startPrice: 68, marketCap: 2.84e11 },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", startPrice: 250, marketCap: 2.81e11 },
  { symbol: "AMD", name: "AMD", sector: "Tech", startPrice: 140, marketCap: 2.72e11 },
  { symbol: "PM", name: "Philip Morris", sector: "Consumer", startPrice: 160, marketCap: 2.64e11 },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials", startPrice: 75, marketCap: 2.58e11 },
  { symbol: "CVX", name: "Chevron", sector: "Energy", startPrice: 150, marketCap: 2.56e11 },
  { symbol: "ABT", name: "Abbott", sector: "Health", startPrice: 115, marketCap: 2.34e11 },
  { symbol: "IBM", name: "IBM", sector: "Tech", startPrice: 250, marketCap: 2.32e11 },
  { symbol: "LIN", name: "Linde", sector: "Materials", startPrice: 450, marketCap: 2.28e11 },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer", startPrice: 300, marketCap: 2.21e11 },
  { symbol: "DIS", name: "Disney", sector: "Media", startPrice: 95, marketCap: 2.14e11 },
  { symbol: "RTX", name: "RTX", sector: "Industrials", startPrice: 150, marketCap: 2.12e11 },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrials", startPrice: 420, marketCap: 2.08e11 },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer", startPrice: 150, marketCap: 2.06e11 },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Health", startPrice: 520, marketCap: 2.02e11 },
  { symbol: "NOW", name: "ServiceNow", sector: "Tech", startPrice: 850, marketCap: 1.98e11 },
  { symbol: "AXP", name: "American Express", sector: "Financials", startPrice: 300, marketCap: 1.96e11 },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health", startPrice: 520, marketCap: 1.92e11 },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials", startPrice: 580, marketCap: 1.88e11 },
  { symbol: "INTU", name: "Intuit", sector: "Tech", startPrice: 650, marketCap: 1.86e11 },
  { symbol: "BKNG", name: "Booking", sector: "Consumer", startPrice: 5200, marketCap: 1.82e11 },
  { symbol: "UBER", name: "Uber", sector: "Consumer", startPrice: 85, marketCap: 1.78e11 },
  { symbol: "AMAT", name: "Applied Materials", sector: "Tech", startPrice: 190, marketCap: 1.74e11 },
];
